### ISSUE TITLE
Reservations 14 days from today don't show

### ISSUE THREAD

**Issue by nvoers** [GiPHouse/Website#617] opened 2023-02-15 10:28 UTC
Reservations that are made exactly 14 days from now do not show in the calendar after they are made. Probably caused by the 14 day limit on reserving rooms.

**Comment by 1058274** [comment] 2023-02-16 10:22
I can confirm after reproducing the bug locally. The reservation is placed correctly, but not shown in the front-end. 

The cause is [here](https://github.com/GiPHouse/Website/blob/main/website/room_reservation/views.py#L137). Suggested fix:

```python
start_time__date__lt=timezone.now() + self.time_window_future,
```
to
```python
start_time__date__lte=timezone.now() + self.time_window_future,
```

**Comment by 1058274** [comment] 2023-02-16 10:33
What is the point of having these filter operations when the dates on which reservations can be made are restricted already?

**Comment by JobDoesburg** [comment] 2023-02-16 10:40
> What is the point of having these filter operations when the dates on which reservations can be made are restricted already?

Otherwise, every time a page is loaded, all reservations ever made will be included (which is very slow)

**Comment by 1058274** [comment] 2023-02-16 10:50
> > What is the point of having these filter operations when the dates on which reservations can be made are restricted already?
> 
> Otherwise, every time a page is loaded, all reservations ever made will be included (which is very slow)

Is there also an argument for the other direction (future reservations)?

**Comment by JobDoesburg** [comment] 2023-02-16 11:41
> > > What is the point of having these filter operations when the dates on which reservations can be made are restricted already?
> > 
> > 
> > Otherwise, every time a page is loaded, all reservations ever made will be included (which is very slow)
> 
> Is there also an argument for the other direction (future reservations)?

I don't think so, there are pretty much never any real future reservations

**Comment by 1058274** [comment] 2023-02-16 11:57
> > > > What is the point of having these filter operations when the dates on which reservations can be made are restricted already?
> > > 
> > > 
> > > Otherwise, every time a page is loaded, all reservations ever made will be included (which is very slow)
> > 
> > 
> > Is there also an argument for the other direction (future reservations)?
> 
> I don't think so, there are pretty much never any real future reservations

In that case, another possible solution is to simply remove the filter condition I refered to earlier, instead of adjusting it.

**Closed** 2023-03-01 07:57 UTC
Labels: bug
